#this Dockerfile is for base php-fpm dev env for xiaoma
FROM wenda/centos
LABEL maintainer="wenda <zhaowd@xiaoma.wang>"
ENV WEBROOT=/data/www \
    PHPREDIS_VERSION=4.0.1

RUN rpm -Uvh https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm \
    && rpm -Uvh https://mirror.webtatic.com/yum/el7/webtatic-release.rpm \
    && yum -y install \
        vim \
        gcc \
        gcc-c++ \
        gcc-gfortran \
        zlib-devel \
        openssl-devel  \
        nghttp2 \
        git \
        curl \
        wget \
        zip \
        unzip \
        net-tools \
        telnet \
        nginx \
        php72w-cli \
        php72w-common \
        php72w-devel \
        php72w-mysql \
        php72w-gd \
        php72w-mbstring \
        php72w-imap \
        php72w-ldap \
        php72w-odbc \
        php72w-bcmath \
        php72w-pear \
        php72w-xml \
        php72w-fpm \
        php72w-pecl-xdebug \
        php72w-opcache \
        libnghttp2-devel \
        nghttp2 \
    \
    && mkdir -p ${WEBROOT}/code \
    && wget http://pecl.php.net/get/redis-${PHPREDIS_VERSION}.tgz -O /tmp/redis.tar.tgz \
    && pecl install /tmp/redis.tar.tgz \
    \
    && echo 'extension=redis.so' > /etc/php.d/redis.ini \
    && echo -e "\ndate.timezone = Asia/Shanghai" >> /etc/php.ini \
    && sed -i "s/listen\.allowed_clients/;listen\.allowed_clients/" /etc/php-fpm.d/www.conf \
    && sed -i 's/listen = 127\.0\.0\.1:9000/listen = 9000/' /etc/php-fpm.d/www.conf \
    && curl -sS https://getcomposer.org/installer | php \
    && mv composer.phar /usr/local/bin/composer \
    && composer self-update --clean-backups \
    \
    && systemctl enable nginx \
    && systemctl enable php-fpm \
    \
    && yum clean all  \
    \
    && rm -f /tmp/redis.tar.tgz \
    && rm -rf /var/cache/yum/*
    

EXPOSE 80 9000

ENTRYPOINT [ "/usr/sbin/init"]
